// OCRs images using the built-in Windows OCR engine (Windows.Media.Ocr).
// Usage: OcrImages <imagesRoot> <outputMarkdown> [--langs en,de]
// Repeatable: re-run whenever gray book images change; output is deterministic
// (sorted by relative path) so diffs stay minimal.

using Windows.Media.Ocr;
using Windows.Storage;
using Windows.Storage.Streams;
using Windows.Graphics.Imaging;

var imagesRoot = args[0];
var outputMd = args[1];

if (!Directory.Exists(imagesRoot))
{
    Console.Error.WriteLine($"Images root not found: {imagesRoot}");
    return 1;
}

var engine = OcrEngine.TryCreateFromLanguage(new Windows.Globalization.Language("en"))
          ?? OcrEngine.TryCreateFromUserProfileLanguages();
if (engine is null)
{
    Console.Error.WriteLine("No OCR engine available (install the English language pack).");
    return 1;
}

var images = Directory
    .GetFiles(imagesRoot, "*.*", SearchOption.AllDirectories)
    .Where(f => f.EndsWith(".png", StringComparison.OrdinalIgnoreCase)
             || f.EndsWith(".jpg", StringComparison.OrdinalIgnoreCase)
             || f.EndsWith(".jpeg", StringComparison.OrdinalIgnoreCase))
    .OrderBy(f => f, StringComparer.OrdinalIgnoreCase)
    .ToList();

Console.WriteLine($"OCR'ing {images.Count} images...");

var sb = new System.Text.StringBuilder();
sb.AppendLine("# Gray Book — Image Text (OCR)");
sb.AppendLine();
sb.AppendLine("> AUTO-GENERATED by scripts/ocr-graybook-images.ps1 — do not edit manually.");
sb.AppendLine("> Text extracted from Gray Book images (screenshots/diagrams) via Windows OCR.");
sb.AppendLine("> Look up image content by its path relative to the Gray Book root.");
sb.AppendLine();
sb.AppendLine("---");
sb.AppendLine();

var ok = 0;
foreach (var img in images)
{
    var rel = Path.GetRelativePath(imagesRoot, img).Replace('\\', '/');
    try
    {
        var text = await OcrFile(img, engine);
        if (string.IsNullOrWhiteSpace(text)) continue;
        ok++;
        sb.AppendLine($"## `{rel}`");
        sb.AppendLine();
        sb.AppendLine(text.Trim());
        sb.AppendLine();
    }
    catch (Exception ex)
    {
        Console.WriteLine($"  skip {rel}: {ex.Message}");
    }
}

await File.WriteAllTextAsync(outputMd, sb.ToString());
Console.WriteLine($"Wrote OCR text for {ok}/{images.Count} images to {outputMd}");
return 0;

static async Task<string> OcrFile(string path, OcrEngine engine)
{
    var file = await StorageFile.GetFileFromPathAsync(path);
    using IRandomAccessStream stream = await file.OpenAsync(FileAccessMode.Read);
    var decoder = await BitmapDecoder.CreateAsync(stream);

    // Downscale if beyond the engine's max dimension
    var maxDim = OcrEngine.MaxImageDimension;
    var w = (int)decoder.PixelWidth;
    var h = (int)decoder.PixelHeight;
    SoftwareBitmap bitmap;
    if (w > maxDim || h > maxDim)
    {
        var scale = (double)maxDim / Math.Max(w, h);
        bitmap = await decoder.GetSoftwareBitmapAsync(
            BitmapPixelFormat.Bgra8, BitmapAlphaMode.Premultiplied,
            new BitmapTransform { ScaledWidth = (uint)(w * scale), ScaledHeight = (uint)(h * scale) },
            ExifOrientationMode.IgnoreExifOrientation, ColorManagementMode.DoNotColorManage);
    }
    else
    {
        bitmap = await decoder.GetSoftwareBitmapAsync(
            BitmapPixelFormat.Bgra8, BitmapAlphaMode.Premultiplied,
            new BitmapTransform(), ExifOrientationMode.IgnoreExifOrientation, ColorManagementMode.DoNotColorManage);
    }

    var result = await engine.RecognizeAsync(bitmap);
    return result.Text;
}
